import:
  - ~/.config/alacritty/catppuccin/window.yml
  - ~/.config/alacritty/catppuccin/colors.yml
  - ~/.config/alacritty/catppuccin/fonts.yml
  - ~/.config/alacritty/catppuccin/cursor.yml
  - ~/.config/alacritty/catppuccin/key_bindings.yml

env:
  TERM: xterm-256color

live_config_reload: true
