window: 
  #dimensions:
  #  columns: 82
  #  lines: 25

  # Just looks nice.
  padding:
    x: 15
    y: 15

  # Removes the MacOS buttons.
  decorations: buttonless
  startup_mode: Windowed
  dynamic_title: true

  # Scrolling
  history: 10000
  multiplier: 3

  # Background opacity
  opacity: 0.9
